extends: substitution
message: Should be '%s', not '%s', but use '{product}' instead.
level: error
ignorecase: false
swap:
  '(?<![`/])(e-attorneys?|e-Attorneys?|eattorneys?|Eattorneys?)(?!`)': eAttorney
  '(?<![`/])(e-courts?|e-Courts?|ecourts?|Ecourts?)(?!`)': eCourt
  '(?<![`/])(e-defenders?|e-Defenders?|edefenders?|Edefenders?)(?!`)': eDefender
  '(?<![`/])(e-prosecutors?|e-Prosecutors?|eprosecutors?|Eprosecutors?)(?!`)': eProsecutor
  '(?<![`/])(e-supervisions?|e-Supervisions?|esupervisions?|Esupervisions?)(?!`)': eSupervision
  '(?<![`/])(e-series|e-Series|eseries|Eseries)(?!`)': eSeries
  '(?<![`/])(e-payit|e-PayIt|ePayIt|ePayit|EPayIt|ePay-It)(?!`)': ePay-it
  '(?<![`/])(e-fileit|e-FileIt|eFileIt|eFileit|EFileIt|eFile-It)(?!`)': eFile-it
